name: k8s-terraform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  AWS_REGION: us-east-1                       # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: api-valhalla-kitchen        # set this to your Amazon ECR repository name
  ECS_CLUSTER: cluster-valhalla-kitchen       # set this to your Amazon ECS cluster name                                              # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: api-valhalla-kitchen        # set this to the name of the container in the
                                              

jobs:
  build:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      id-token: write 
      contents: read
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::075131957861:role/github-role
          aws-region: us-east-1  

      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     cli_config_credentials_token: 1.4.6

      # - name: Terraform Init
      #   id: init
      #   run: terraform init
      
      # - name: Terraform Validate
      #   id: validate
      #   run: terraform validate -no-color

      # - name: Terraform Plan
      #   id: plan
      #   if: github.event_name == 'pull_request'
      #   run: terraform plan -no-color -input=false
      #   continue-on-error: true

      # - name: Terraform Plan Status
      #   if: steps.plan.outcome == 'failure'
      #   run: exit 1

      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform apply -auto-approve -input=false
      #   continue-on-error: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
    
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: renanfee
          REPOSITORY: api-valhalla-kitchen
          IMAGE_TAG: latest
        run: |
          docker build . -t $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
    
      - name: Update kube config
        run: aws eks update-kubeconfig --name primuslearning
      
      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernets

