name: k8s-terraform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  AWS_REGION: us-east-1                       
  ECR_REPOSITORY: api-valhalla-kitchen        
  ECS_CLUSTER: cluster-valhalla-kitchen       
  CONTAINER_NAME: api-valhalla-kitchen        
                                              

jobs:
  build:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      id-token: write 
      contents: read
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest
        id: install

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::075131957861:role/github-role
          aws-region: us-east-1  

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: 1.4.6
      - name: Terraform Init
        id: init
        run: terraform init
  
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        continue-on-error: true

      - name: Login to Amazon ECR
        id: login-ecr-aws
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create ECR repository
        env:
          REPO_NAME: api-valhalla-kitchen
          REGION: us-east-1
        run: |
          aws ecr create-repository --repository-name $REPO_NAME --region $REGION

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr-aws.outputs.registry }}
          REPOSITORY: api-valhalla-kitchen
          REGION: us-east-1
          IMAGE_TAG: latest
        run: |
          docker build . -t $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
    
      - name: Update kube config
        run: aws eks update-kubeconfig --name cluster-valhalla-kitchen --region us-east-1
        continue-on-error: true

      - name: Deploy to EKS
        run: |
          kubectl apply -f ./k8s
          kubectl get nodes
          kubectl get deployments -A
        continue-on-error: true     

      - name: Terraform Destroy
        run: terraform destroy -auto-approve


